/**
 * Product 위젯 공용 목업 데이터
 */
const productData = [
  {
    id: 1,
    name: '상품명 1',
    brand: '브랜드명 1',
    price: '80',
    discountPrice: '80',
    originalPrice: '100',
    discountRate: 20,
    image: '/images/products/product-1.png',
    soldOut: false,
  },
  {
    id: 2,
    name: '상품명 2',
    brand: '브랜드명 2',
    price: '85',
    discountPrice: '85',
    originalPrice: '100',
    discountRate: 15,
    image: '/images/products/product-2.png',
    soldOut: false,
  },
  {
    id: 3,
    name: '상품명 3',
    brand: '브랜드명 3',
    price: '90',
    discountPrice: '90',
    originalPrice: '100',
    discountRate: 10,
    image: '/images/products/product-3.png',
    soldOut: false,
  },
  {
    id: 4,
    name: '상품명 4',
    brand: '브랜드명 4',
    price: '75',
    discountPrice: '75',
    originalPrice: '100',
    discountRate: 25,
    image: '/images/products/product-4.png',
    soldOut: false,
  },
  {
    id: 5,
    name: '상품명 5',
    brand: '브랜드명 5',
    price: '95',
    discountPrice: '95',
    originalPrice: '100',
    discountRate: 5,
    image: '/images/products/product-5.png',
    soldOut: false,
  },
  {
    id: 6,
    name: '상품명 6',
    brand: '브랜드명 6',
    price: '70',
    discountPrice: '70',
    originalPrice: '100',
    discountRate: 30,
    image: '/images/products/product-6.png',
    soldOut: false,
  },
  {
    id: 7,
    name: '상품명 7',
    brand: '브랜드명 7',
    price: '65',
    discountPrice: '65',
    originalPrice: '100',
    discountRate: 35,
    image: '/images/products/product-7.png',
    soldOut: false,
  },
  {
    id: 8,
    name: '상품명 8',
    brand: '브랜드명 8',
    price: '88',
    discountPrice: '88',
    originalPrice: '100',
    discountRate: 12,
    image: '/images/products/product-8.png',
    soldOut: false,
  },
  {
    id: 9,
    name: '상품명 9',
    brand: '브랜드명 9',
    price: '92',
    discountPrice: '92',
    originalPrice: '100',
    discountRate: 8,
    image: '/images/products/product-9.png',
    soldOut: false,
  },
  {
    id: 10,
    name: '상품명 10',
    brand: '브랜드명 10',
    price: '78',
    discountPrice: '78',
    originalPrice: '100',
    discountRate: 22,
    image: '/images/products/product-1.png',
    soldOut: false,
  },
  {
    id: 11,
    name: '상품명 11',
    brand: '브랜드명 11',
    price: '82',
    discountPrice: '82',
    originalPrice: '100',
    discountRate: 18,
    image: '/images/products/product-2.png',
    soldOut: false,
  },
  {
    id: 12,
    name: '상품명 12',
    brand: '브랜드명 12',
    price: '88',
    discountPrice: '88',
    originalPrice: '100',
    discountRate: 12,
    image: '/images/products/product-3.png',
    soldOut: false,
  },
]

// 전역으로 노출
window.productData = productData
